from flask import Flask, render_template, request, redirect, url_for, flash
import sqlite3
import datetime

app = Flask(__name__)
@app.route("/")


def home():

    # need to get all data form the database
    # connect to the database
    database_file_name = "fol.db"
    connection = sqlite3.connect(database_file_name)


    # get a cursor to the database
    cursor = connection.cursor()

    # execute a query to get all the data from the database
    query = "SELECT * FROM people"

    # get the results
    cursor = connection.execute(query)
    results = cursor.fetchall()
    # close the cursor/database
    connection.close()

    # for debugging remove this when finished
    print(results)

    return render_template("home.html", people=results)

@app.route("/insert",methods=["POST", "GET"])
def insert():
    if request.method == "POST":

        # get the data from the form
        name = request.form["name"]
        email = request.form["email"]
        # get address_1 from request.form
        address = request.form["address_1"]
        address_1 = request.form["address_2"]
        city = request.form["city"]
        postcode= request.form["postcode"]
        state = request.form["state"]
        phone = request.form["phone"]
        dob = request.form["dob"]


        # TODO: DEAL WITH Dob

        # dob is in the format "YYYY-MM-DD"
        # need to convert to timestamp https://www.geeksforgeeks.org/converting-string-yyyy-mm-dd-into-datetime-in-python/
        # https://www.w3schools.com/python/python_datetime.asp

        date_format = "%Y-%m-%d" # this is the format we are converting from.
        date_of_birth = datetime.datetime.strptime(dob, date_format)

        '''
        FYI - need to use later to convert from timestamp to date
         datetime.utcfromtimestamp(dob_timestamp).strftime("%d/%m/%Y")
        '''



        # connect to the database
        database_file_name = "fol.db"
        connection = sqlite3.connect(database_file_name)

        # query to insert into database
        query = "INSERT INTO people (name, email, address, address_1, city, postcode, state, phone, dob) " \
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"

        data = (name, email, address, address_1, city, postcode, state, phone, date_of_birth)
        # get a cursor to the database
        cursor = connection.cursor()
        # run query
        cursor.execute(query)
        person_id = cursor.lastrowid
        # commit the changes

        connection.commit()

        # TODO: deal with locations
        locations = request.form["locations"]
        # for debug - remove when finished
        print(locations)
        # need to get the list.
        locations = request.form.getlist("locations")

        # for debug - remove when finished
        print(locations)
        for location in locations:
            # assumes that the locations are the ID of the location
            # need to have auto generated select box for this.

            query = "INSERT INTO people_at_locations (card_num, location_id) VALUES (?, ?);"
            data = (person_id, location)

            cursor.execute(query, data)
            connection.commit()


        # close the cursor/database
        connection.close()


    # autogenerated select box
    # get the data to create the select box
    # connect to the database
    database_file_name = "fol.db"
    connection = sqlite3.connect(database_file_name)
    # get the cursor
    cursor = connection.cursor()
    query = "SELECT id, name FROM locations"
    cursor.execute(query)
    locations = cursor.fetchall()
    # close the cursor/database
    connection.close()

    return render_template("insert.html", locations=locations)


if __name__ == "__main__":
    app.run(debug=True)
    #app.run()